import type {NextPage} from 'next'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {ChatAlt2Icon, PlusIcon} from '@heroicons/react/solid';
import {useEffect, useState} from "react";
import axios from "axios";


export default function Home() {
	const [movies, setMovies] = useState([])

	useEffect(() => {
		//TODO: change the url to get-movies endpoint
		axios.get('http://185.110.189.42:5000/get-movies')
			.then(function (response: any) {
				// handle success
				setMovies(response.data.movies)
			})
			.catch(function (error: any) {
				// handle error
				console.log(error);
			})
			.then(function () {
				// always executed
			});
	}, []);


	return (
		<div className = {styles.container}>
			<Head>
				<title>Movies</title>
				<meta name = "description" content = "Generated by create next app"/>
				<link rel = "icon" href = "/favicon.ico"/>
			</Head>

			<main className = {styles.main}>
				<h1 className = {styles.title}>
					Welcome to movies page!
				</h1>

				<p className = {styles.description}>
					Get started by selecting a movie and comment on it or checkout its comments
				</p>

				<ul role = "list" className = "grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
					{movies.map(({title, director, genre, poster}) => (
						<li
							key = {title}
							className = "col-span-1 flex flex-col text-center bg-white rounded-lg shadow divide-y divide-gray-200"
						>
							<div className = "flex-1 flex flex-col p-8">
								<img className = "w-32 h-32 flex-shrink-0 mx-auto rounded" src = {poster}
								     alt = ""/>
								<h3 className = "mt-6 text-gray-900 text-sm font-medium">{title}</h3>
								<dl className = "mt-1 flex-grow flex flex-col justify-between">
									<dt className = "sr-only">Director</dt>
									<dd className = "text-gray-500 text-sm">{director}</dd>
									<dt className = "sr-only">Genre</dt>
									<dd className = "mt-3">
                <span className = "px-2 py-1 text-blue-800 text-xs font-medium bg-blue-100 rounded-full">
                  {genre}
                </span>
									</dd>
								</dl>
							</div>
							<div>
								<div className = "-mt-px flex divide-x divide-gray-200">
									<div className = "-ml-px w-96 flex-1 flex">
										<a
											href={`comments/${title}`}
											className = "relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500"
										>
											<ChatAlt2Icon className = "w-5 h-5 text-gray-400" aria-hidden = "true"/>
											<span className = "ml-3">Show comments</span>
										</a>
									</div>
									<div className = "-ml-px w-0 flex-1 flex">
										<a
											href = {`/addComment?movie=${title}`}
											className = "relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500"
										>
											<PlusIcon className = "w-5 h-5 text-gray-400" aria-hidden = "true"/>
											<span className = "ml-3">Add a comment</span>
										</a>
									</div>
								</div>
							</div>
						</li>

					))}
				</ul>


			</main>

		</div>
	)
}

